/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function m(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:m(a)}}var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=ba(this);function v(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var h=a[d];if(!(h in c))break a;c=c[h]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}var w;
if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var x;a:{var ca={a:!0},y={};try{y.__proto__=ca;x=y.a;break a}catch(a){}x=!1}w=x?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var z=w;
function B(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(z)z(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.I=b.prototype}function C(){this.m=!1;this.j=null;this.h=void 0;this.g=1;this.s=this.i=0;this.l=null}function D(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}C.prototype.o=function(a){this.h=a};
function E(a,b){a.l={exception:b,H:!0};a.g=a.i||a.s}C.prototype.return=function(a){this.l={return:a};this.g=this.s};function F(a,b,c){a.g=c;return{value:b}}function G(a){a.i=0;var b=a.l.exception;a.l=null;return b}function da(a){this.g=new C;this.h=a}function ea(a,b){D(a.g);var c=a.g.j;if(c)return H(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return I(a)}
function H(a,b,c,d){try{var h=b.call(a.g.j,c);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.g.m=!1,h;var l=h.value}catch(f){return a.g.j=null,E(a.g,f),I(a)}a.g.j=null;d.call(a.g,l);return I(a)}function I(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.h=void 0,E(a.g,c)}a.g.m=!1;if(a.g.l){b=a.g.l;a.g.l=null;if(b.H)throw b.exception;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function fa(a){this.next=function(b){D(a.g);a.g.j?b=H(a,a.g.j.next,b,a.g.o):(a.g.o(b),b=I(a));return b};this.throw=function(b){D(a.g);a.g.j?b=H(a,a.g.j["throw"],b,a.g.o):(E(a.g,b),b=I(a));return b};this.return=function(b){return ea(a,b)};this[Symbol.iterator]=function(){return this}}function ha(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,h){function l(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(l,h)}l(a.next())})}
function J(a){return ha(new fa(new da(a)))}v("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(l||"")+"_"+h++,l)}function c(l,f){this.g=l;q(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",h=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=r[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&q(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ia(m(this))}})}return a});function ia(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
v("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.o=!1;var e=this.j();try{f(e.resolve,e.reject)}catch(g){e.reject(g)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(e){e(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var e=this;this.i(function(){e.l()})}this.g.push(f)};var h=r.setTimeout;c.prototype.i=function(f){h(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var e=0;e<f.length;++e){var g=
f[e];f[e]=null;try{g()}catch(k){this.j(k)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(k){return function(n){g||(g=!0,k.call(e,n))}}var e=this,g=!1;return{resolve:f(this.A),reject:f(this.l)}};b.prototype.A=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.F(f);else{a:switch(typeof f){case "object":var e=null!=f;break a;case "function":e=!0;break a;default:e=!1}e?this.v(f):this.m(f)}};
b.prototype.v=function(f){var e=void 0;try{e=f.then}catch(g){this.l(g);return}"function"==typeof e?this.G(e,f):this.m(f)};b.prototype.l=function(f){this.s(2,f)};b.prototype.m=function(f){this.s(1,f)};b.prototype.s=function(f,e){if(0!=this.h)throw Error("Cannot settle("+f+", "+e+"): Promise already settled in state"+this.h);this.h=f;this.i=e;2===this.h&&this.B();this.C()};b.prototype.B=function(){var f=this;h(function(){if(f.D()){var e=r.console;"undefined"!==typeof e&&e.error(f.i)}},1)};b.prototype.D=
function(){if(this.o)return!1;var f=r.CustomEvent,e=r.Event,g=r.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof e?f=new e("unhandledrejection",{cancelable:!0}):(f=r.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return g(f)};b.prototype.C=function(){if(null!=this.g){for(var f=0;f<this.g.length;++f)l.h(this.g[f]);this.g=null}};var l=new c;b.prototype.F=
function(f){var e=this.j();f.u(e.resolve,e.reject)};b.prototype.G=function(f,e){var g=this.j();try{f.call(e,g.resolve,g.reject)}catch(k){g.reject(k)}};b.prototype.then=function(f,e){function g(u,A){return"function"==typeof u?function(R){try{k(u(R))}catch(S){n(S)}}:A}var k,n,t=new b(function(u,A){k=u;n=A});this.u(g(f,k),g(e,n));return t};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.u=function(f,e){function g(){switch(k.h){case 1:f(k.i);break;case 2:e(k.i);break;default:throw Error("Unexpected state: "+
k.h);}}var k=this;null==this.g?l.h(g):this.g.push(g);this.o=!0};b.resolve=d;b.reject=function(f){return new b(function(e,g){g(f)})};b.race=function(f){return new b(function(e,g){for(var k=p(f),n=k.next();!n.done;n=k.next())d(n.value).u(e,g)})};b.all=function(f){var e=p(f),g=e.next();return g.done?d([]):new b(function(k,n){function t(R){return function(S){u[R]=S;A--;0==A&&k(u)}}var u=[],A=0;do u.push(void 0),A++,d(g.value).u(t(u.length-1),n),g=e.next();while(!g.done)})};return b});
function K(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
v("WeakMap",function(a){function b(g){this.g=(e+=Math.random()+1).toString();if(g){g=p(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function d(g){var k=typeof g;return"object"===k&&null!==g||"function"===k}function h(g){if(!K(g,f)){var k=new c;q(g,f,{value:k})}}function l(g){var k=Object[g];k&&(Object[g]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&h(n);return k(n)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),k=Object.seal({}),
n=new a([[g,2],[k,3]]);if(2!=n.get(g)||3!=n.get(k))return!1;n.delete(g);n.set(k,4);return!n.has(g)&&4==n.get(k)}catch(t){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var e=0;b.prototype.set=function(g,k){if(!d(g))throw Error("Invalid WeakMap key");h(g);if(!K(g,f))throw Error("WeakMap key fail: "+g);g[f][this.g]=k;return this};b.prototype.get=function(g){return d(g)&&K(g,f)?g[f][this.g]:void 0};b.prototype.has=function(g){return d(g)&&K(g,
f)&&K(g[f],this.g)};b.prototype.delete=function(g){return d(g)&&K(g,f)&&K(g[f],this.g)?delete g[f][this.g]:!1};return b});
v("Map",function(a){function b(){var e={};return e.previous=e.next=e.head=e}function c(e,g){var k=e.g;return ia(function(){if(k){for(;k.head!=e.g;)k=k.previous;for(;k.next!=k.head;)return k=k.next,{done:!1,value:g(k)};k=null}return{done:!0,value:void 0}})}function d(e,g){var k=g&&typeof g;"object"==k||"function"==k?l.has(g)?k=l.get(g):(k=""+ ++f,l.set(g,k)):k="p_"+g;var n=e.h[k];if(n&&K(e.h,k))for(e=0;e<n.length;e++){var t=n[e];if(g!==g&&t.key!==t.key||g===t.key)return{id:k,list:n,index:e,entry:t}}return{id:k,
list:n,index:-1,entry:void 0}}function h(e){this.h={};this.g=b();this.size=0;if(e){e=p(e);for(var g;!(g=e.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),g=new a(p([[e,"s"]]));if("s"!=g.get(e)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var k=g.entries(),n=k.next();if(n.done||n.value[0]!=e||"s"!=n.value[1])return!1;n=k.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!k.next().done?!1:!0}catch(t){return!1}}())return a;var l=new WeakMap;h.prototype.set=function(e,g){e=0===e?0:e;var k=d(this,e);k.list||(k.list=this.h[k.id]=[]);k.entry?k.entry.value=g:(k.entry={next:this.g,previous:this.g.previous,head:this.g,key:e,value:g},k.list.push(k.entry),this.g.previous.next=k.entry,this.g.previous=k.entry,this.size++);return this};h.prototype.delete=function(e){e=d(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.h[e.id],
e.entry.previous.next=e.entry.next,e.entry.next.previous=e.entry.previous,e.entry.head=null,this.size--,!0):!1};h.prototype.clear=function(){this.h={};this.g=this.g.previous=b();this.size=0};h.prototype.has=function(e){return!!d(this,e).entry};h.prototype.get=function(e){return(e=d(this,e).entry)&&e.value};h.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};h.prototype.keys=function(){return c(this,function(e){return e.key})};h.prototype.values=function(){return c(this,
function(e){return e.value})};h.prototype.forEach=function(e,g){for(var k=this.entries(),n;!(n=k.next()).done;)n=n.value,e.call(g,n[1],n[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var f=0;return h});
v("Set",function(a){function b(c){this.g=new Map;if(c){c=p(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(p([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var h=d.entries(),l=h.next();if(l.done||l.value[0]!=c||l.value[1]!=c)return!1;l=h.next();return l.done||l.value[0]==c||4!=l.value[0].x||
l.value[1]!=l.value[0]?!1:h.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var h=this;this.g.forEach(function(l){return c.call(d,l,l,h)})};return b});v("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(e){return e};var h=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof l){b=l.call(b);for(var f=0;!(l=b.next()).done;)h.push(c.call(d,l.value,f++))}else for(l=b.length,f=0;f<l;f++)h.push(c.call(d,b[f],f));return h}});var ja=this||self;function L(a){this.locked=a}function M(a){this.errorType=a}M.prototype.toString=function(){return this.errorType};function ka(a){this.errorType="This Chrome API is not available";this.call=a}B(ka,M);function N(a,b){this.errorType="Error executing Chrome API";this.call=a;this.message=b||""}B(N,M);N.prototype.toString=function(){return this.call+" returned '"+this.message+"'"};function la(){this.errorType="Tab is not locked"}B(la,M);
function ma(){this.errorType="Devtools cannot be open when locking"}B(ma,M);function na(){this.errorType="Unknown command"}B(na,M);function O(a){this.errorType="Unknown Error";this.exception=oa(a)}B(O,M);O.prototype.toString=function(){return M.prototype.toString.call(this)+(this.exception.message?". Details: '"+this.exception.message+"'":"")};function oa(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=a[c]});return b};function P(a){for(var b=void 0,c=ja,d=p(a.split(".")),h=d.next();!h.done;h=d.next())if(h=h.value,b=c,c=c[h],void 0==c)return function(){return Promise.reject(new ka(a))};return function(l){var f=Array.prototype.slice.call(arguments);return new Promise(function(e,g){f.push(function(k){if(chrome.runtime.lastError)g(new N(a,chrome.runtime.lastError.message));else switch(arguments.length){case 0:e(void 0);break;case 1:e(arguments[0]);break;default:e(Array.prototype.slice.call(arguments))}});c.apply(b,
f)})}};var Q=new function(){this.m=P("chrome.tabs.discard");this.v=P("chrome.tabs.query");this.D=P("chrome.tabs.move");this.A=P("chrome.tabs.reload");this.B=P("chrome.tabs.update");this.createWindow=P("chrome.windows.create");this.s=P("chrome.windows.getCurrent");this.C=P("chrome.windows.get");this.j=P("chrome.windows.update");this.o=P("chrome.management.getAll");this.h=P("chrome.management.setEnabled");P("chrome.storage.local.clear");this.l=P("chrome.storage.local.get");this.g=P("chrome.storage.local.remove");
this.i=P("chrome.storage.local.set")};function pa(a){var b;return J(function(c){if(1==c.g)return F(c,Q.l(a),2);b=c.h;return c.return(b[a])})}function qa(){var a=null;a=void 0===a?{}:a;var b;return J(function(c){if(1==c.g)return F(c,pa("savedTab"),2);b=c.h;return c.return(b||a)})}function ra(a){var b=void 0;b=void 0===b?[]:b;var c;return J(function(d){if(1==d.g)return F(d,pa(a),2);c=d.h;return d.return(c||b)})}
function sa(a){var b=void 0===b?new Set:b;var c;return J(function(d){if(1==d.g)return F(d,ra(a),2);c=d.h;return d.return(c&&c.length?new Set(c):b)})}function T(a,b){var c={};return Q.i((c[a]=b,c))};var U=Promise.resolve();function V(){return J(function(a){U=U.then(ta);return a.return(U)})}function ta(){return J(function(a){return a.return(sa("activeTabs"))})}function ua(a){return J(function(b){U=U.then(function(){return T("activeTabs",Array.from(a))});return b.return(U)})}function va(){return Q.g("activeTabs")}
function wa(a){var b,c;return J(function(d){if(1==d.g){b=a;if(b.data&&"object"===typeof b.data)switch(c=b.data,c.type){case "devtools-opened":case "devtools-closed":d.g=3;return;default:console.warn("Unknown message: "+c.type)}else console.warn("Unknown message type: "+b.data);d.g=0}else return 5!=d.g?d=F(d,xa(c.type,c.tabId),5):(d.g=0,d=void 0),d})}
function xa(a,b){var c;return J(function(d){if(1==d.g)return b?F(d,V(),2):d.return();c=d.h;switch(a){case "devtools-opened":c.add(b);break;case "devtools-closed":c.delete(b)}return F(d,ua(c),0)})}function ya(a){var b;return J(function(c){if(1==c.g)return F(c,V(),2);b=c.h;return c.return(b.has(a))})};var za=new Set("gndmhdcefbhlchkhipcnnbkcmicncehk ifajfiofeifbbhbionejdliodenmecna imgmjcnolbhljlnimjbnmeokfljgjokj haldlgldplgnggkjaafhelgiaglafanh hjngolefdpdnooamgdldlkjgmdcmcjnc ckanlcmoklgdobgbkebohpficpiogcif kbohafcopfpigkjdimdcdgenlhkmhbnc hmfjajhcddnpmhkhakkgoibealjcffho kmffehbidlalibfeklaefnckpidbodff fabpdabkjmplhckhfhknoemeihjffobe mnehmlglkdbpcimikacjgegmpebacoab ajphlblkfpppdpkgokiejbjfohfohhmk inoeonmfapjbbkmdafoankkfajkcphgd ikfigngpioedjjooplekefdiilaokaik iheobagjkfklnlikgihanlhcddjoihkg mloajfnmjckfjbeeofcdaecbelnblden emmgndmggimgmmpciejhnkcnlillakfn unit-test:allowed-extension-id".split(" ")),
Aa=new Set(["unit-test:disallowed-extension-id"]),W;W=Promise.resolve();
function Ba(){var a,b,c,d;return J(function(h){switch(h.g){case 1:return F(h,Q.o(),2);case 2:return a=h.h,b=a.filter(Ca).map(function(l){return l.id}),c=new Set(b),F(h,T("disabledExtensions",Array.from(c)),3);case 3:return d=b.map(function(l){var f;return J(function(e){if(1==e.g)return e.i=2,F(e,Q.h(l,!1),4);2!=e.g?(e.g=0,e.i=0):(f=G(e),console.warn("Error disabling "+l+" ("+f+")"),c.delete(l),e.g=0)})}),F(h,Promise.all(d),4);case 4:return F(h,T("disabledExtensions",Array.from(c)),0)}})}
function Ca(a){return a.enabled&&"extension"==a.type?Aa.has(a.id)?!0:"admin"==a.installType||za.has(a.id)?!1:!0:!1}function Da(){return J(function(a){W=W.then(Ba);return a.return(W)})}function Ea(){var a,b;return J(function(c){return 1==c.g?F(c,sa("disabledExtensions"),2):3!=c.g?(a=c.h,b=Array.from(a).map(function(d){return J(function(h){if(1==h.g)return F(h,Q.h(d,!0),2);a.delete(d);h.g=0})}),F(c,Promise.all(b),3)):F(c,T("disabledExtensions",Array.from(a)),0)})}function Fa(){return W=W.then(Ea)};function Ga(a){var b;return J(function(c){if(1==c.g)return F(c,Q.v({discarded:!1}),2);b=c.h;return c.return(Promise.all(b.filter(function(d){return d.id!=a}).map(function(d){return Q.m(d.id)})))})};function X(){var a;return J(function(b){if(1==b.g)return F(b,qa(),2);a=b.h;return b.return(a)})}Promise.resolve();
function Ha(a){var b,c,d;return J(function(h){switch(h.g){case 1:return F(h,ya(a.id),2);case 2:if(b=h.h)throw console.warn("Devtools detected in tab "+a.id),new ma;h.i=3;return F(h,Q.createWindow({type:"popup",state:"fullscreen",tabId:a.id,incognito:a.incognito}),5);case 5:return c=h.h,F(h,Q.j(c.id,{state:"locked-fullscreen"}),6);case 6:var l={};l=Q.i((l.savedTab=a,l));return F(h,l,7);case 7:return F(h,Promise.all([Ga(a.id),Da()]),8);case 8:h.g=4;h.i=0;break;case 3:return d=G(h),F(h,Y(a),9);case 9:throw d;
case 4:return Q.A(a.id),F(h,Ia(),10);case 10:return h.return(new L(!0))}})}function Ja(a){var b;return J(function(c){if(1==c.g)return F(c,X(),2);if(3!=c.g){b=c.h;if(null==b||b.id!=a.id)throw new la;return F(c,Y(b),3)}return c.return(new L(!1))})}function Y(a){return J(function(b){if(1==b.g)return F(b,Q.g("savedTab"),2);if(3!=b.g)return F(b,Promise.all([Fa(),Ka(a)]),3);chrome.webNavigation.onCommitted.hasListener(Z)&&chrome.webNavigation.onCommitted.removeListener(Z);b.g=0})}
function Ka(a){var b,c;return J(function(d){switch(d.g){case 1:return F(d,Q.s(),2);case 2:return b=d.h,F(d,Q.j(b.id,{state:"fullscreen"}),3);case 3:return d.i=4,F(d,Q.C(a.windowId),6);case 6:d.g=5;d.i=0;break;case 4:return G(d),F(d,Q.createWindow({type:"normal",state:"normal",tabId:a.id,incognito:a.incognito}),7);case 7:return d.return();case 5:return F(d,Q.D(a.id,{index:a.index,windowId:a.windowId}),8);case 8:return c=d.h,F(d,Q.B(c.id,{active:!0}),0)}})}
function La(a){var b;return J(function(c){if(1==c.g)return F(c,Ma(a),2);b=c.h;return c.return(new L(b))})}function Ma(a){var b;return J(function(c){if(1==c.g)return F(c,X(),2);b=c.h;return c.return(!!b&&b.id==a.id)})}
function Z(a){var b;return J(function(c){if(1==c.g)return 0!==a.frameId?c.return():F(c,X(),2);b=c.h;if(!b)return console.warn("The navigation listener was installed without a locked tab."),c.return();if(b.id!=a.tabId)return console.log("A navigation to "+a.url+" occurred in tab "+a.tabId+", which is not the locked tab."),c.return();if(Na(a.url))return c.return();console.warn("An unauthorized navigation to "+a.url+" occurred in tab "+a.tabId);return F(c,Y(b),0)})}
function Ia(){var a;return J(function(b){if(1==b.g)return F(b,X(),2);a=b.h;if(!a)return b.return();chrome.webNavigation.onCommitted.hasListener(Z)||chrome.webNavigation.onCommitted.addListener(Z);b.g=0})}function Na(a){return(chrome.runtime.getManifest().externally_connectable.matches||[]).map(function(b){b=new URLPattern(b);return new URLPattern({hostname:b.hostname,pathname:b.pathname,protocol:b.protocol})}).some(function(b){return b.test(a)})};function Oa(a,b,c,d,h){d=d instanceof M?d:new O(d);console.error("Extension "+chrome.runtime.id+" returned error: '"+d+"' in response to request: '"+a.command+"' from tab "+b+" with url "+c);h(d)};J(function(a){chrome.runtime.onStartup.addListener(va);chrome.tabs.onRemoved.addListener(function(b){var c;return J(function(d){if(1==d.g)return F(d,V(),2);c=d.h;c.delete(b);return F(d,ua(c),0)})});self.addEventListener("message",wa);a.g=0});chrome.runtime.onStartup.addListener(Fa);
J(function(a){chrome.tabs.onRemoved.addListener(function(b){var c;return J(function(d){if(1==d.g)return F(d,X(),2);if((c=d.h)&&c.id==b)return console.warn("Tab "+b+" was closed while locked"),F(d,Y(c),0);d.g=0})});return F(a,Ia(),0)});
chrome.runtime.onMessageExternal.addListener(function(a,b,c){if(b.tab)try{console.log("Extension "+chrome.runtime.id+" received request: '"+a.command+"' from tab "+b.tab.id+" with url "+b.tab.url);switch(a.command){case "lock":var d=Ha(b.tab);break;case "isLocked":d=La(b.tab);break;case "unlock":d=Ja(b.tab);break;default:throw new na;}d.then(function(h){console.log("Extension "+chrome.runtime.id+" returned response: "+JSON.stringify(h)+" to request: '"+a.command+"'");c(h)},function(h){return Oa(a,
b.tab.id,b.tab.url,h,c)});return!0}catch(h){Oa(a,b.tab.id,b.tab.url,h,c)}});console.log("Loaded extension "+chrome.runtime.id+", version "+chrome.runtime.getManifest().version+".");
